### ISSUE TITLE
Tutorial.ipynb: TypeError 

### ISSUE THREAD

**Issue by dtchang** [learningmatter-mit/GLAMOUR#1]
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
~\AppData\Local\Temp/ipykernel_4700/4262452729.py in <module>
----> 1 unsup.edit_distance(NX_GRAPHS['GBID10271'], NX_GRAPHS['GBID10330'])

TypeError: edit_distance() missing 3 required positional arguments: 'node_attr', 'edge_attr', and 'upper_bound'

**Comment by pikulsomesh** [comment]
The `unsup.edit_distance` line in the [Tutorial notebook](https://github.com/learningmatter-mit/GLAMOUR/blob/main/Tutorial.ipynb) has been updated to include explicit information about the three arguments.
