### ISSUE TITLE
Tutorial.ipynb: IndexError

### ISSUE THREAD

**Issue by dtchang** [learningmatter-mit/GLAMOUR#2]
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
~\AppData\Local\Temp/ipykernel_4044/2280642386.py in <module>
      3     NX_GRAPHS = NX_GRAPHS,
      4     DF_PATH = DF_PATH,
----> 5     method = 'UMAP')

~\Desktop\DL-KG-MM\glamour\utils\macro_unsupervised.py in plot_embeddings(embeddings, NX_GRAPHS, DF_PATH, method)
    194 
    195     for idx, graph_id in enumerate(NX_GRAPHS):
--> 196         if df[df.ID == graph_id]['Immunogenic'].tolist()[0] == 'Yes':
    197             immunogenic_idx.append(idx)
    198             colors.append('#B12122')

IndexError: list index out of range

**Comment by pikulsomesh** [comment]
Updated the table path in the [Tutorial](https://github.com/learningmatter-mit/GLAMOUR/blob/main/Tutorial.ipynb) from `'./tables/glycobase_immuno_mini.txt'` to `'./tables/glycobase_immuno.txt'`

The index error was arising from the mini-data set not having a specific glycan.
