### ISSUE TITLE
Tutorial: PermissionError (Note: the .pth file was created by the code)

### ISSUE THREAD

**Issue by dtchang** [learningmatter-mit/GLAMOUR#3]
---------------------------------------------------------------------------
PermissionError                           Traceback (most recent call last)
~\AppData\Local\Temp/ipykernel_15340/2459103388.py in <module>
----> 1 macro_supervised.main()

~\Desktop\DL-KG-MM\glamour\utils\macro_supervised.py in main(self)
    362             early_stop = stopper.step(
    363                 val_score[list(val_score.keys())[0]],
--> 364                 model, optimizer, self._model_name, self._save_model, self._save_opt)
    365 
    366             print('epoch {:d}/{:d}, validation {} {:.4f}, best validation {} {:.4f}, '.format(

~\Desktop\DL-KG-MM\glamour\utils\stopper.py in step(self, score, model, optimizer, modelname, save_model, save_opt)
     77         if self.best_score is None:
     78             self.best_score = score
---> 79             self.save_checkpoint(model, optimizer, modelname, save_model, save_opt)
     80         elif self._check(score, self.best_score):
     81             self.best_score = score

~\Desktop\DL-KG-MM\glamour\utils\stopper.py in save_checkpoint(self, model, optimizer, modelname, save_model, save_opt)
    101         save_opt : boolean, whether to save optimizer
    102         '''
--> 103         torch.save({'model_state_dict': model.state_dict()}, self._filename)
    104 
    105         if save_model == True:

C:\Anaconda3\lib\site-packages\torch\serialization.py in save(obj, f, pickle_module, pickle_protocol, _use_new_zipfile_serialization)
    374     _check_dill_version(pickle_module)
    375 
--> 376     with _open_file_like(f, 'wb') as opened_file:
    377         if _use_new_zipfile_serialization:
    378             with _open_zipfile_writer(opened_file) as opened_zipfile:

C:\Anaconda3\lib\site-packages\torch\serialization.py in _open_file_like(name_or_buffer, mode)
    228 def _open_file_like(name_or_buffer, mode):
    229     if _is_path(name_or_buffer):
--> 230         return _open_file(name_or_buffer, mode)
    231     else:
    232         if 'w' in mode:

C:\Anaconda3\lib\site-packages\torch\serialization.py in __init__(self, name, mode)
    209 class _open_file(_opener):
    210     def __init__(self, name, mode):
--> 211         super(_open_file, self).__init__(open(name, mode))
    212 
    213     def __exit__(self, *args):

PermissionError: [Errno 13] Permission denied: 'C:\\Users\\dtchang\\Desktop\\DL-KG-MM\\glamour\\model2k1qlxdd.pth'

**Comment by pikulsomesh** [comment]
This is a common problem on Windows while running the code from a non-administrator user account. 
Check - https://github.com/jupyter/notebook/issues/4907

**Comment by dtchang** [comment]
My user account is administrator. The problem occurs in Jupyter or  
Spider. It is caused by torch.save() and torch.load(). After commenting out the following two lines in stopper.py, the code runs fine:
torch.save({'model_state_dict': model.state_dict()}, self._filename)
model.load_state_dict(torch.load(self._filename)['model_state_dict'])
