### ISSUE TITLE
macro_attribution.py: NameError

### ISSUE THREAD

**Issue by dtchang** [learningmatter-mit/GLAMOUR#5]
---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
~\AppData\Local\Temp/ipykernel_18412/4066727375.py in <module>
      1 attribution.plot_graph(
      2     input_graph = input_graph,
----> 3     NX_GRAPHS = NX_GRAPHS)

~\Desktop\DL-KG-MM\glamour\utils\macro_attribution.py in plot_graph(self, input_graph, NX_GRAPHS)
    148         NX_GRAPHS : dict, dictionary of networkx graphs
    149         """
--> 150         self.dgl_graph = dgl_graph
    151         self.NX_GRAPHS = NX_GRAPHS
    152 

NameError: name 'dgl_graph' is not defined

**Comment by pikulsomesh** [comment]
This has been updated in the last commit. Updating the local repo should make it work.

**Comment by dtchang** [comment]
This issue still exists. With the current repo, dgl_graph on line 150 is undefined:

    def plot_graph(self, input_graph, NX_GRAPHS):
        """
        Displays graph of macromolecule with node weights corresponding to node size.

        Args:
        input_graph : input DGL graph, macromolecule graph 
        NX_GRAPHS : dict, dictionary of networkx graphs
        """
        self.dgl_graph = dgl_graph

**Comment by dtchang** [comment]
The following change resolves the issue:
        self.dgl_graph = input_graph
