### ISSUE TITLE
Issue #5

### ISSUE THREAD

**Issue by dtchang** [learningmatter-mit/GLAMOUR#7]
This issue still exists. With the current repo, dgl_graph on line 150 is undefined:

def plot_graph(self, input_graph, NX_GRAPHS):
    """
    Displays graph of macromolecule with node weights corresponding to node size.

    Args:
    input_graph : input DGL graph, macromolecule graph 
    NX_GRAPHS : dict, dictionary of networkx graphs
    """
    self.dgl_graph = dgl_graph

The following change resolves the issue:
    self.dgl_graph = input_graph

**Comment by pikulsomesh** [comment]
Updated.
