### ISSUE TITLE
Issue #6

### ISSUE THREAD

**Issue by dtchang** [learningmatter-mit/GLAMOUR#8]
I think it is only appropriate that you update the code to work with newer versions (> 3.2.x) of Matplotlib (current 3.5.1). Version requirement should be forward compatible, which is commonly supported and, in your case, is supported for all other dependencies (Python, PyTorch, etc.).

**Comment by pikulsomesh** [comment]
Thanks for pointing it out! It should be a trivial change based on what version you intend to use.
